name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set environment variable
        run: echo "API_KEY=${{ vars.API_KEY }}" >> $GITHUB_ENV

      - name: Run the script
        run: node set-env.js
